{% set name = "csp-adapter-slack" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/csp-adapter-slack/csp_adapter_slack-{{ version }}.tar.gz
  sha256: 374761dc956b472d1744230f8669858642199decd968d4d7da912bcf1a24d423

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - csp
    - pydantic
    - slack-sdk >=3

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - csp_adapter_slack

about:
  home: http://github.com/point72/csp-adapter-slack
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A csp adapter for slack
  description: A csp adapter for slack
  dev_url: http://github.com/point72/csp-adapter-slack

extra:
  recipe-maintainers:
    - timkpaine
